version: "2.2"

networks:
  mifos:
    driver: bridge
services:  
  mifos-otp:
    image: harbor.infotec.mx/mifosio/com.mx.infotec.otp.develop
    restart: always
    extra_hosts:
      - "tidb:172.22.216.194"
    ports:
      - 2050:2050  
    networks:
      - mifos
